name: build

on:
  workflow_call:
    inputs:
      dockerfile_path:
        description: 'Dockerfile path (e.g. ./s3c/Dockerfile)'
        required: true
        type: string
      image_suffix:
        description: 'Image name suffix (e.g. the s3c part of tools-s3c)'
        required: true
        type: string
    outputs:
      digest:
        value: ${{ jobs.build.outputs.digest }}

permissions:
  contents: read

jobs:
  build:
    outputs:
      digest: ${{ steps.image.outputs.digest }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:

    - name: Checkout Code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2

    - name: Set Variables
      run: |
        echo "RELEASE_VERSION=$(cat .version)" >> $GITHUB_ENV
        echo "IMAGE_URI=ghcr.io/${{ github.repository }}-${{ inputs.image_suffix }}" >> $GITHUB_ENV

    - name: Auth Docker
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc  # v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e  # v4.4.0
      with:
        images: ${{ env.IMAGE_URI }}
        tags: |
          type=raw,enable=true,value=${{ env.RELEASE_VERSION }}
          type=raw,enable=true,value=latest

    - name: BuildPush Image
      id: build
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671  # v4.0.0
      with:
        context: .
        file: ${{ inputs.dockerfile_path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Output Digest
      id: image
      run: |
        echo "digest=${{ env.IMAGE_URI }}@${{ steps.build.outputs.digest }}" >> "$GITHUB_OUTPUT"
