name: build

on:
  workflow_call:
    inputs:
      dockerfile_path:
        description: 'Dockerfile path (e.g. ./s3c/Dockerfile)'
        required: true
        type: string
      image_suffix:
        description: 'Image name suffix (e.g. the s3c part of tools-s3c)'
        required: true
        type: string
      image_version:
        description: 'Image version (e.g. v0.0.1)'
        required: true
        type: string
    outputs:
      digest:
        value: ${{ jobs.build.outputs.digest }}

permissions:
  contents: read

jobs:
  build:
    outputs:
      digest: ${{ steps.image.outputs.digest }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:

    - name: Checkout Code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2

    - name: Auth Docker
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a  # v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96  # v4.3.0
      with:
        images: ghcr.io/${{ github.repository }}-${{ inputs.image_suffix }}
        tags: |
          type=raw,enable=true,value=${{ inputs.image_version }}
          type=raw,enable=true,value=latest

    - name: BuildPush Image
      id: build
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671  # v4.0.0
      with:
        context: .
        file: ${{ inputs.dockerfile_path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Output Digest
      id: image
      run: |
        echo "digest=${{ env.IMG_URI }}@${{ steps.build.outputs.digest }}" >> "$GITHUB_OUTPUT"
