name: release
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'  # Only build tag with semantic versioning format

permissions:
  contents: read

jobs:

  conf:
    env:
      # Update as needed
      COSIGN_VERSION: v2.0.1
      ERR_VULNERABILITY_SEV: 'CRITICAL,HIGH,MEDIUM'

    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      image_version: ${{ steps.conf.outputs.image_version }}
      cosign_version: ${{ steps.conf.outputs.cosign_version }}
      err_on_vulnerability_sev: ${{ steps.conf.outputs.err_on_vulnerability_sev }}
    steps:
    - name: Export Config
      id: conf
      run: |
        echo "image_version=$(cat .version)" >> $GITHUB_OUTPUT
        echo "cosign_version=${{ env.COSIGN_VERSION }}" >> $GITHUB_OUTPUT
        echo "err_on_vulnerability_sev=${{ env.ERR_VULNERABILITY_SEV }}" >> $GITHUB_OUTPUT

  build-s3c:
    needs:
    - conf
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yaml
    with:
      dockerfile_path: s3c/Dockerfile
      image_suffix: s3c
      image_version: ${{ needs.conf.outputs.image_version }}

  sign:
    needs:
    - conf
    - build-s3c
    permissions:
      contents: read
      actions: read
      packages: write
    uses: ./.github/workflows/sign.yaml
    with:
      cosign_version: ${{ needs.conf.outputs.cosign_version }}
      image_digest: ${{ needs.build.outputs.digest }}

  scan:
    needs:
    - conf
    - build-s3c
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/scan.yaml
    with:
      image_digest: ${{ needs.build.outputs.digest }}
      scan_severity: ${{ needs.conf.outputs.err_on_vulnerability_sev }}

  slsa:
    needs:
    - conf
    - build-s3c
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    uses: ./.github/workflows/slsa.yaml
    with:
      image_digest: ${{ needs.build.outputs.digest }}
