name: release
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'  # Only build tag with semantic versioning format

permissions:
  contents: read

jobs:

  build_s3c:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yaml
    with:
      dockerfile_path: s3c/Dockerfile
      image_suffix: s3c
      image_version: "${GITHUB_REF#refs/*/}"

  attest_s3c:
    needs:
    - build_s3c
    permissions:
      contents: read
      actions: read
      packages: write
    uses: ./.github/workflows/attest.yaml
    with:
      image_digest: ${{ needs.build_s3c.outputs.digest }}
