name: sbom

on:
  workflow_call:
    inputs:
      image_digest:
        description: 'Fully-qualified image digest to verify (registry/image@sha256:digest)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: write
    steps:

    - uses: anchore/sbom-action@4d571ad1038a9cc29d676154ef265ab8f9027042  # v0.14.2
      with:
        image: ${{ inputs.image_digest }}
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        artifact-name: sbom.spdx
